nonstop/urls.py
from django.urls import path, re_path, reverse_lazy
from django.views.generic import RedirectView

from .views import (
    AddSomaDiffusionView,
    AjaxProgram,
    ArtistDetailView,
    ArtistEditView,
    ArtistListView,
    ArtistTracksMetadataView,
    CleanupView,
    DelSomaDiffusionView,
    DiffusionPropertiesView,
    JingleAddView,
    JingleSettingsView,
    JinglesListView,
    MuninTracks,
    QuickLinksView,
    RandomFillGenderTracksMetadataView,
    RandomTracksMetadataView,
    RecentTracksMetadataView,
    RecurringAddPlaylistView,
    RecurringAddStreamView,
    RecurringDeleteView,
    RecurringEditPlaylistView,
    RecurringView,
    RedirectTodayView,
    SearchCsvView,
    SearchView,
    SomaDayArchiveCsvView,
    SomaDayArchiveView,
    StatisticsView,
    StreamAddView,
    StreamDeleteView,
    StreamEditView,
    StreamsListView,
    TapePartEditView,
    TapePartRemoveView,
    TapeTrackAddView,
    TrackDetailView,
    TrackEditView,
    TracksAddToZoneView,
    TrackToTapeView,
    UploadTracksView,
    ZoneAddView,
    ZoneDeleteView,
    ZoneEditorialSettings,
    ZoneSettings,
    ZonesView,
    ZoneTracklistPercents,
    force_switch_view,
    jingle_audio_view,
    track_sound,
)

urlpatterns = [
    path('', QuickLinksView.as_view(), name='nonstop-quick-links'),
    path('today/', RedirectTodayView.as_view(), name='nonstop-today'),
    path('stats/', StatisticsView.as_view(), name='nonstop-stats'),
    path('tracks/<int:pk>/', TrackDetailView.as_view(), name='track-view'),
    path('tracks/<int:pk>/edit/', TrackEditView.as_view(), name='track-edit'),
    path('tracks/<int:pk>/sound/', track_sound, name='nonstop-track-sound'),
    path('tracks/<int:pk>/mark-as-tape/', TrackToTapeView.as_view(), name='nonstop-track-to-tape'),
    path('tape/<int:pk>/add', TapeTrackAddView.as_view(), name='tape-track-add'),
    path('tape/<int:pk>/edit', TapePartEditView.as_view(), name='tape-part-edit'),
    path('tape/<int:pk>/remove', TapePartRemoveView.as_view(), name='tape-part-remove'),
    path('artists/', ArtistListView.as_view(), name='artist-list'),
    path('artists/<int:pk>/', ArtistDetailView.as_view(), name='artist-view'),
    path('artists/<int:pk>/edit/', ArtistEditView.as_view(), name='artist-edit'),
    path('jingles/', JinglesListView.as_view(), name='nonstop-jingles-list'),
    path('jingles/add/', JingleAddView.as_view(), name='nonstop-jingle-add'),
    path('jingles/<int:pk>/', JingleSettingsView.as_view(), name='nonstop-jingle-settings'),
    path('zones/', ZonesView.as_view(), name='nonstop-zones'),
    path('zones/new', ZoneAddView.as_view(), name='nonstop-zone-add'),
    re_path(r'^zones/(?P<slug>[\w-]+)/settings/$', ZoneSettings.as_view(), name='zone-settings'),
    re_path(
        r'^zones/(?P<slug>[\w-]+)/editorial/$',
        ZoneEditorialSettings.as_view(),
        name='zone-editorial-settings',
    ),
    re_path(r'^zones/(?P<slug>[\w-]+)/delete/$', ZoneDeleteView.as_view(), name='nonstop-zone-delete'),
    path('streams/', StreamsListView.as_view(), name='nonstop-streams'),
    path('streams/add/', StreamAddView.as_view(), name='nonstop-stream-add'),
    path('streams/<int:pk>/', StreamEditView.as_view(), name='nonstop-stream-edit'),
    path('streams/<int:pk>/delete/', StreamDeleteView.as_view(), name='nonstop-stream-delete'),
    # Example: /2012/nov/10/
    re_path(
        r'^(?P<year>[0-9]{4})/(?P<month>[-\w]+)/(?P<day>[0-9]+)/$',
        SomaDayArchiveView.as_view(),
        name="archive_day",
    ),
    re_path(
        r'^(?P<year>[0-9]{4})/(?P<month>[-\w]+)/(?P<day>[0-9]+)/csv$',
        SomaDayArchiveCsvView.as_view(),
        name="archive_day_csv",
    ),
    path('upload/', UploadTracksView.as_view(), name='nonstop-upload-tracks'),
    path('metadata/recent/', RecentTracksMetadataView.as_view(), name='nonstop-recent-tracks'),
    path('metadata/random/', RandomTracksMetadataView.as_view(), name='nonstop-random-tracks'),
    path(
        'metadata/random/gender',
        RandomFillGenderTracksMetadataView.as_view(),
        name='nonstop-fill-gender-random-tracks',
    ),
    path(
        'metadata/artist/<int:artist_pk>/',
        ArtistTracksMetadataView.as_view(),
        name='nonstop-artist-metadata-tracks',
    ),
    path('search/', SearchView.as_view(), name='nonstop-search'),
    path('search/csv', SearchCsvView.as_view(), name='nonstop-search-csv'),
    path('search/add-to-zone', TracksAddToZoneView.as_view(), name='nonstop-search-add-to-zone'),
    path('quick-links/', RedirectView.as_view(url=reverse_lazy('nonstop-quick-links'))),
    path('cleanup/', CleanupView.as_view(), name='nonstop-cleanup'),
    path('force-switch/', force_switch_view, name='nonstop-force-switch'),
    # soma management for episodes
    path('diffusion/<int:pk>/add/', AddSomaDiffusionView.as_view(), name='nonstop-add-diffusion'),
    path(
        'diffusion/<int:pk>/properties/',
        DiffusionPropertiesView.as_view(),
        name='nonstop-diffusion-properties',
    ),
    path('diffusion/<int:pk>/del/', DelSomaDiffusionView.as_view(), name='nonstop-del-diffusion'),
    path('api/jingle/<int:pk>/', jingle_audio_view, name='jingle-audio-view'),
    re_path(
        r'^recurring/emission/(?P<slug>[\w-]+)/$', RecurringView.as_view(), name='nonstop-recurring-stuff'
    ),
    re_path(
        r'^recurring/emission/(?P<slug>[\w-]+)/add-stream/$',
        RecurringAddStreamView.as_view(),
        name='nonstop-recurring-add-stream',
    ),
    re_path(
        r'^recurring/emission/(?P<slug>[\w-]+)/add-playlist/$',
        RecurringAddPlaylistView.as_view(),
        name='nonstop-recurring-add-playlist',
    ),
    re_path(
        r'^recurring/emission/(?P<slug>[\w-]+)/edit-playlist/$',
        RecurringEditPlaylistView.as_view(),
        name='nonstop-recurring-edit-playlist',
    ),
    re_path(
        r'^recurring/emission/(?P<slug>[\w-]+)/delete/$',
        RecurringDeleteView.as_view(),
        name='nonstop-recurring-delete',
    ),
    # ajax parts
    re_path(
        r'^ajax/zones/(?P<slug>[\w-]+)/percents/$',
        ZoneTracklistPercents.as_view(),
        name='nonstop-ajax-zone-percents',
    ),
]

public_urlpatterns = [
    re_path(r'^api/munin/tracks/(?P<config>config/)?$', MuninTracks.as_view()),
    re_path(r'^ajax/program/(?P<date>[\d-]*)$', AjaxProgram.as_view(), name='nonstop-ajax-program'),
]

nonstop/models.py
import collections
import datetime
import json
import os
import random

from django.conf import settings
from django.core.files.storage import default_storage
from django.db import models
from django.db.models.signals import post_delete, post_save
from django.dispatch import receiver
from django.urls import reverse
from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _
from emissions.utils import get_duration

from .app_settings import app_settings


class Artist(models.Model):
    name = models.CharField(_('Name'), max_length=255)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('artist-view', kwargs={'pk': self.id})

    def recent_diffusions(self):
        return (
            SomaLogLine.objects.filter(track__artist=self)
            .exclude(on_air=False)
            .order_by('-play_timestamp')
            .select_related('track')
            .select_related('track__artist')
        )

    def active_tracks(self):
        return self.track_set.filter(nonstop_zones__isnull=False).distinct().order_by('title')

    def available_tracks(self):
        return self.track_set.filter(nonstop_zones__isnull=True).order_by('title')


class Album(models.Model):
    name = models.CharField(_('Name'), max_length=255)


LANGUAGES = [
    ('en', _('English')),
    ('fr', _('French')),
    ('nl', _('Dutch')),
    ('other', _('Other')),
    ('na', _('Not applicable')),
]


class Track(models.Model):
    title = models.CharField(_('Title'), max_length=255)
    artist = models.ForeignKey(Artist, null=True, on_delete=models.SET_NULL)
    album = models.ForeignKey(Album, null=True, on_delete=models.SET_NULL)
    instru = models.BooleanField(_('Instru'), default=False)
    language = models.CharField(_('Language'), max_length=10, choices=LANGUAGES, blank=True)
    sabam = models.BooleanField('SABAM', default=True)
    cfwb = models.BooleanField('CFWB', default=False)

    # gender metadata
    gender_m = models.PositiveSmallIntegerField(_('(cis)Male members'), blank=True, null=True)
    gender_f = models.PositiveSmallIntegerField(_('(cis)Female members'), blank=True, null=True)
    gender_x = models.PositiveSmallIntegerField(
        _('Non-binary, trans or agender members'), blank=True, null=True
    )
    gender_l = models.CharField(
        _('Lead'),
        choices=[
            ('m', _('Male')),
            ('f', ('Female')),
            ('x', _('Non-binary, trans or agender')),
        ],
        blank=True,
        null=True,
    )
    gender_m_computed_score = models.FloatField(blank=True, null=True)
    gender_f_computed_score = models.FloatField(blank=True, null=True)
    gender_x_computed_score = models.FloatField(blank=True, null=True)

    nonstop_zones = models.ManyToManyField('emissions.Nonstop', blank=True)

    creation_timestamp = models.DateTimeField(auto_now_add=True, null=True)
    added_to_nonstop_timestamp = models.DateTimeField(null=True)
    uploader = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, on_delete=models.SET_NULL)

    soundfile = models.FileField(
        _('File'), upload_to='nonstop/tracks/%Y-%m', max_length=255, null=True, blank=True
    )
    duration = models.DurationField(_('Duration'), null=True)

    class Meta:
        ordering = ['creation_timestamp']

    def __str__(self):
        return 'Track %s (%s)' % (self.title, self.artist or 'unknown')

    def save(self, *args, **kwargs):
        self.gender_m_computed_score = None
        self.gender_f_computed_score = None
        self.gender_x_computed_score = None
        total = (self.gender_m or 0) + (self.gender_f or 0) + (self.gender_x or 0)
        if total:
            self.gender_m_computed_score = (self.gender_m or 0) / total
            self.gender_f_computed_score = (self.gender_f or 0) / total
            self.gender_x_computed_score = (self.gender_x or 0) / total
            if self.gender_l and self.gender_l != 'N':  # lead
                self.gender_m_computed_score /= 2
                self.gender_f_computed_score /= 2
                self.gender_x_computed_score /= 2
                if self.gender_l == 'M':
                    self.gender_m_computed_score += 0.5
                if self.gender_l == 'F':
                    self.gender_f_computed_score += 0.5
                if self.gender_l == 'X':
                    self.gender_x_computed_score += 0.5
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('track-view', kwargs={'pk': self.id})

    def recent_diffusions(self):
        return (
            SomaLogLine.objects.filter(track=self)
            .exclude(on_air=False)
            .order_by('-play_timestamp')
            .select_related('track')
            .select_related('track__artist')
        )

    def file_path(self):
        if self.soundfile and self.soundfile.path:
            return self.soundfile.path
        return None

    def file_exists(self):
        file_path = self.file_path()
        if not file_path:
            return False
        try:
            return os.path.exists(file_path)
        except AttributeError:
            return False

    def match_criteria(self, criteria, weight_value):
        return getattr(self, 'match_criteria_' + criteria)()

    def match_criteria_lang_en(self):
        return self.language == 'en'

    def match_criteria_lang_fr(self):
        return self.language == 'fr'

    def match_criteria_lang_nl(self):
        return self.language == 'nl'

    def match_criteria_lang_other(self):
        return self.language == 'other'

    def match_criteria_instru(self):
        return self.instru

    def match_criteria_cfwb(self):
        return self.cfwb

    def match_criteria_newest(self):
        if not self.added_to_nonstop_timestamp:
            return False
        now = datetime.datetime.now()
        return (now - self.added_to_nonstop_timestamp).days < 30

    def match_criteria_new(self):
        if not self.added_to_nonstop_timestamp:
            return False
        now = datetime.datetime.now()
        return (now - self.added_to_nonstop_timestamp).days < 100


class Tape(models.Model):
    # single file referencing real tracks
    full_track = models.ForeignKey(Track, on_delete=models.CASCADE)
    parts = models.ManyToManyField(Track, through='TapePart', related_name='tapes')

    def get_parts(self):
        return TapePart.objects.filter(tape=self.id).order_by('position')


class TapePart(models.Model):
    tape = models.ForeignKey(Tape, on_delete=models.CASCADE)
    track = models.ForeignKey(Track, on_delete=models.CASCADE)
    position = models.DurationField(_('Position'), null=True, blank=True)

    def __str__(self):
        return f'{self.track} @ {self.position} in {self.tape.full_track.title}'


class SomaLogLine(models.Model):
    class Meta:
        verbose_name = _('Soma log line')
        verbose_name_plural = _('Soma log lines')
        ordering = ['play_timestamp']

    track = models.ForeignKey(Track, null=True, on_delete=models.SET_NULL)
    play_timestamp = models.DateTimeField()
    on_air = models.BooleanField('On Air', null=True)
    channel = models.CharField('Channel', max_length=255, blank=True, null=True)


class Jingle(models.Model):
    class Meta:
        verbose_name = _('Jingle')
        verbose_name_plural = _('Jingles')
        ordering = ['label']

    label = models.CharField(_('Label'), max_length=100)
    filepath = models.CharField(_('File Path'), max_length=255, blank=True)
    soundfile = models.FileField(
        _('File'), upload_to='nonstop/jingles/', max_length=255, null=True, blank=True
    )
    duration = models.DurationField(_('Duration'), null=True, blank=True)
    clock_time = models.TimeField(_('Clock Time'), null=True, blank=True)
    default_for_initial_diffusions = models.BooleanField(_('Default for initial diffusions'), default=False)
    default_for_reruns = models.BooleanField(_('Default for reruns'), default=False)
    default_for_streams = models.BooleanField(_('Default for streams'), default=False)
    emission = models.ForeignKey('emissions.Emission', null=True, blank=True, on_delete=models.SET_NULL)
    exclude_from_episodes = models.BooleanField(_('Exclude from episodes selection'), default=False)

    def __str__(self):
        if self.duration:
            return '%s (%ds)' % (self.label, self.duration.total_seconds())
        return self.label

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.soundfile:
            self.duration = datetime.timedelta(seconds=float(get_duration(self.get_local_filepath())))
            super().save(*args, **kwargs)

    @property
    def short(self):
        # property for compatibility with Track model
        # for jingles self.filepath is actually only the last part of the path,
        # ex: jingles panik/H_marimba_RP_chucho_zoe.wav
        if self.soundfile:
            return os.path.split(self.soundfile.name)[-1]
        return self.filepath

    def file_path(self):
        # for compatibility with Track model method
        return self.get_local_filepath()

    def get_local_filepath(self):
        if not self.short:
            return None
        if self.soundfile:
            return default_storage.path(self.soundfile.name)
        return os.path.join(app_settings.LOCAL_BASE_PATH, app_settings.JINGLES_PREFIX, self.short)

    @property
    def title(self):
        return self.label


class Stream(models.Model):
    class Meta:
        verbose_name = _('Stream')
        verbose_name_plural = _('Streams')
        ordering = ['label']

    label = models.CharField(_('Label'), max_length=100)
    url = models.URLField(_('URL'), max_length=255)

    def __str__(self):
        return self.label


class ScheduledDiffusion(models.Model):
    class Meta:
        verbose_name = _('Scheduled diffusion')

nonstop/templates/nonstop/artist_detail.html
{% extends "base.html" %}
{% load i18n %}

{% block page-title %}{{ object.name }} | Nonstop | {{ block.super }}{% endblock %}

{% block appbar %}
  <h2>Nonstop - {{ object.name }}</h2>
  {% if perms.nonstop.add_track %}
    <span class="actions">
      <a data-popup href="{% url 'artist-edit' pk=object.id %}">{% trans "Edit" %}</a>
    </span>
  {% endif %}
{% endblock %}

{% block more-user-links %}
  {{ block.super }}
  <a class="button icon-music" href="{% url 'nonstop-quick-links' %}">{% trans "Nonstop management" %}</a>
{% endblock %}

{% block content %}

  <div class="section">
    <h3>{% trans "Most recently played" %}</h3>

    <ul class="soma-list">
      {% for somalog in object.recent_diffusions|slice:":20" %}
        <li><span class="timestamp">{{ somalog.play_timestamp|date:"d/m/Y H:i" }}</span>:
          {% if somalog.track %}
            <a href="{{ somalog.track.get_absolute_url }}" class="tracktitle">{{ somalog.track.title }}</a>
            <span class="trackartist">(<a href="{{ somalog.track.artist.get_absolute_url }}" class="trackartist">{{ somalog.track.artist.name }}</a>)</span>
          {% endif %}
          <span class="filepath">{{ somalog.track.soundfile }}</span>
        </li>
      {% empty %}
        <li><i>{% trans "(none)" %}</i></li>
      {% endfor %}
    </ul>
  </div>

  <div class="section">
    <h3>{% trans "Active tracks" %}</h3>

    <ul>
      {% for track in object.active_tracks %}
        <li><a href="{{ track.get_absolute_url }}" class="tracktitle">{{ track.title }}</a>
          ({% for zone in track.nonstop_zones.all %}{{zone}}{% if not forloop.last %}, {% endif %}{% endfor %})
        </li>
      {% empty %}
        <li><i>{% trans "(none)" %}</i></li>
      {% endfor %}
    </ul>
  </div>


  <div class="section">
    <h3>{% trans "Available tracks" %}</h3>

    <ul>
      {% for track in object.available_tracks %}
        <li><a href="{{ track.get_absolute_url }}" class="tracktitle">{{ track.title }}</a></li>
      {% empty %}
        <li><i>{% trans "(none)" %}</i></li>
      {% endfor %}
    </ul>
  </div>

{% endblock %}

{% block sidebar %}
  <aside id="sidebar">
    <p>
      <a class="button" href="{% url 'nonstop-artist-metadata-tracks' artist_pk=object.id %}">{% trans "Update tracks metadata" %}</a>
    </p>
  </aside>
{% endblock %}

nonstop/templates/nonstop/artist_list.html
{% extends "base.html" %}
{% load i18n %}

{% block page-title %}{% trans "Artists" %} | Nonstop | {{ block.super }}{% endblock %}

{% block appbar %}
  <h2>Nonstop - {% trans "Artists" %}</h2>
{% endblock %}

{% block more-user-links %}
  {{ block.super }}
  <a class="button icon-music" href="{% url 'nonstop-quick-links' %}">{% trans "Nonstop management" %}</a>
{% endblock %}

{% block content %}

  <form id="artist-search">
    {{ form.as_p }}
    <button>{% trans 'Filter' context "action" %}</button>
  </form>

  <div class="section">
    <ul class="artists-list">
      {% for artist in object_list %}
        <li><a href="{% url 'artist-view' pk=artist.id %}">{{ artist.name }}</a></li>
      {% endfor %}
    </ul>
  </div>

{% endblock %}

nonstop/templates/nonstop/jingle_form.html
{% extends "base.html" %}
{% load i18n %}

{% block appbar %}
  <h2>{% trans "Jingle" %}</h2>
{% endblock %}

{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="buttons">
      <button class="submit-button">{% if object.id %}{% trans "Save" %}{% else %}{% trans "Add" %}{% endif %}</button>
      <a class="cancel" href=".">{% trans "Cancel" %}</a>
    </div>
  </form>
{% endblock %}

nonstop/templates/nonstop/somalogline_archive_day.html
{% extends "base.html" %}
{% load i18n %}

{% block page-title %}{% trans "Playlist" %} {{ day|date:"d/m/Y" }} | Nonstop | {{ block.super }}{% endblock %}

{% block appbar %}
  <h2>Nonstop - {{ day|date:"d/m/Y" }}</h2>
  <span class="actions"><a href="csv" download="export-{{ day|date:"Y-m-d" }}.csv">{% trans "CSV export" %}</a></span>
{% endblock %}

{% block more-user-links %}
  {{ block.super }}
  <a class="button icon-music" href="{% url 'nonstop-quick-links' %}">{% trans "Nonstop management" %}</a>
{% endblock %}

{% block content %}

  <div class="section">
    <ul class="soma-list">
      {% for somalog in object_list %}
        <li class="on-air-{{ somalog.on_air }} {% if somalog.track.tape_set.exists %}track-is-tape{% endif %}"><span class="timestamp">{{ somalog.play_timestamp|date:"H:i" }}</span>:
          {% if somalog.track %}
            <a href="{{ somalog.track.get_absolute_url }}" class="tracktitle">{{ somalog.track.title }}</a>
            <span class="trackartist">(<a href="{{ somalog.track.artist.get_absolute_url }}" class="trackartist">{{ somalog.track.artist.name }}</a>)</span>
          {% endif %}
        </li>
      {% endfor %}
    </ul>
  </div>

  <p>
    {% if previous_day %}
      <a href="{% url 'archive_day' year=previous_day.year month=previous_day.month day=previous_day.day %}">{% trans "Previous Day" %}</a>
    {% endif %}
    {% if previous_day and next_day %}--{% endif %}
    {% if next_day %}
      <a href="{% url 'archive_day' year=next_day.year month=next_day.month day=next_day.day %}">{% trans "Next Day" %}</a>
    {% endif %}
  </p>

{% endblock %}

nonstop/templates/nonstop/track_detail.html
{% extends "base.html" %}
{% load gadjo i18n %}

{% block page-title %}{{ object.title }} | {{ object.artist.name }} | Nonstop | {{ block.super }}{% endblock %}

{% block appbar %}
  <h2>Nonstop - {{ object.artist.name }} / {{ object.title }}</h2>
  {% if perms.nonstop.add_track %}
    <span class="actions">
      <a data-popup href="{% url 'track-edit' pk=object.id %}">{% trans "Edit artist/title" %}</a>
      {% if tape_mode_enabled and object.file_exists and object.duration.total_seconds > 300 and not object.tape_set.exists %}
        <a href="{% url 'nonstop-track-to-tape' pk=object.id %}">{% trans "Enable tape mode" %}</a>
      {% endif %}
    </span>
  {% endif %}
{% endblock %}

{% block more-user-links %}
  {{ block.super }}
  <a class="button icon-music" href="{% url 'nonstop-quick-links' %}">{% trans "Nonstop management" %}</a>
{% endblock %}

{% block content %}

  {% if object.file_exists %}
    <audio preload="none" src="{% url "nonstop-track-sound" pk=object.id %}" controls></audio>
  {% elif object.tapes.exists %}
    <div class="infonotice">
      {% trans "The track is part of a tape." %}
      → <a href="{% url 'track-view' pk=object.tapes.first.full_track.id %}">{% trans "View" %}</a>
    </div>
  {% else %}
    <div class="infonotice">
      {% trans "The track is no longer available on the server." %}
    </div>
  {% endif %}

  {% if object.tape_set.exists %}
    <div class="section">
      <h3>{% trans "Tape" %}</h3>
      {% with object.tape_set.all.0 as tape %}
        <ul>
          {% for part in tape.get_parts %}
            <li>
              {% if perms.nonstop.add_track %}
                <a data-popup class="icon-edit" href="{% url 'tape-part-edit' pk=part.id %}"><span class="sr-only">{% trans "edit" %}</span></a>
                <a data-popup class="icon-remove" href="{% url 'tape-part-remove' pk=part.id %}"><span class="sr-only">{% trans "remove" %}</span></a>
              {% endif %}
              {{ part.position }} - <a href="{% url 'track-view' pk=part.track.id %}">{{ part.track.artist.name }} - {{ part.track.title }}</a>
            </li>
          {% endfor %}
          <li><a data-popup href="{% url 'tape-track-add' pk=tape.id %}">{% trans "Add to tape contents" %}</a></li>
        </ul>
      {% endwith %}
    </div>
  {% endif %}

  {% if object.recent_diffusions %}
    <div class="section">

      <ul class="soma-list">
        {% for somalog in object.recent_diffusions|slice:":20" %}
          <li><span class="timestamp">{{ somalog.play_timestamp|date:"d/m/Y H:i" }}</span>:
            {% if somalog.track %}
              <a href="{{ somalog.track.get_absolute_url }}" class="tracktitle">{{ somalog.track.title }}</a>
              <span class="trackartist">(<a href="{{ somalog.track.artist.get_absolute_url }}" class="trackartist">{{ somalog.track.artist.name }}</a>)</span>
            {% endif %}
            <span class="filepath">{{ somalog.track.soundfile }}</span>
          </li>
        {% endfor %}
      </ul>
    </div>
  {% endif %}

{% endblock %}

{% block sidebar %}
  <aside id="sidebar">

    <h3>{% trans "Metadata" %}</h3>

    {% if object.artist %}
      <p>{% trans "Artist:" %}<br><a href="{% url "artist-view" pk=object.artist.id %}">{{ object.artist.name }}</a></p>
    {% endif %}

    {% if object.duration %}
      <p>{% trans "Duration:" %} {{object.duration}}</p>
    {% endif %}

    {% if object.creation_timestamp %}
      <p>{% trans "Uploaded on:" %} {{object.creation_timestamp|date:"SHORT_DATE_FORMAT" }}</p>
    {% endif %}

    {% if perms.nonstop.add_track %}
      <form method="POST">
        {% csrf_token %}
        {{ metadata_form|with_template }}
        {% if not object.file_exists %}
          <style>#id_nonstop_zones_p { display: none; }</style>

        {% endif %}
        {% if object.added_to_nonstop_timestamp %}
          <p>
            {% blocktrans with date=object.added_to_nonstop_timestamp|date:"SHORT_DATE_FORMAT" %}
              In nonstop since {{ date }}.
            {% endblocktrans %}
          </p>
        {% endif %}

        <div class="buttons">
          <button class="submit-button">{% trans "Update" %}</button>
        </div>
        <script>
          $(function() {
            $('[name=language]').on('change', function() {
              $('[name=instru]').prop('checked', $(this).val() == 'na');
            });
            $('[name=instru').on('change', function() {
              if ($(this).is(':checked') && $('[name=language]').val() != 'na') {
                $('[name=language]').val('na');
              }
              if (! $(this).is(':checked') && $('[name=language]').val() == 'na') {
                $('[name=language]').val('');
              }
            });
          });

        </script>
        <style>
          ul#id_nonstop_zones, #id_nonstop_zones li {
            margin: 0;
            padding: 0;
            list-style: none;
          }
        </style>
      </form>
    {% endif %}
  </aside>

{% endblock %}